version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11
    working_directory: /go/src/github.com/tizz98/godash
    steps:
    - checkout
    - run: make test
    - run: make build
    - run: cp config.example.yaml config.yaml
    - run: ./dash version
